### ISSUE TITLE
reading .ineb files 

### ISSUE THREAD

**Issue by feltre** [feltre/FITS_files_creation#1]
Do you have a routine that reads the .ineb files in python (I have only one in cpp)?
If not, never mind, I will write one myself and I will then create the fits files as discussed!
@jacopo-chevallard

**Comment by jacopo-chevallard** [comment]
Nope, I have one in Fortran, not in Python... Let me know if you need help!

**Comment by JuliaGutkin** [comment]
As you know I have it in C++ (one to read the ineb, and also one for the ised) but not in Python.
